version: '3'

services:

  # A container for the Postgresql DB
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      # Postgresql
      - 54321:5432    
